[package]
name = "browser"
version = "0.1.0"
edition = "2021"

[dependencies]
webkit = { package = "webkit6", version = "0.2.0" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.adw]
package = "libadwaita"
version = "0.5.3"
